server:
  port: 9090
spring:
  datasource:
    username: furn
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/furn?useSSL=true&useUnicode=true&characterEncoding=UTF-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl